import * as THREE from "three";
import { RonEngine, CharacterController, BoxCollider, Component, Lighting, Material } from "../../engine/RonEngine.js";

const engine = new RonEngine({ quality: "high", maxPixelRatio: 2 });
const world = engine.scene.threeScene;
world.name = "Ron Range"; world.background = new THREE.Color(0x050b11); world.fog = new THREE.Fog(0x050b11, 24, 100);
Lighting.ambient(world, 0x92bdd8, .42); const sun = Lighting.sun(world, [14, 24, 10], 2.4); sun.shadow.camera.left = sun.shadow.camera.bottom = -35; sun.shadow.camera.right = sun.shadow.camera.top = 35;
const scoreNode = document.querySelector('#score'), comboNode = document.querySelector('#combo'), ammoNode = document.querySelector('#ammo'), hint = document.querySelector('#hint'), cross = document.querySelector('#cross'), pauseScreen = document.querySelector('#pause');

function box(name, p, size, color, collider = true) { const entity = engine.createEntity(name); entity.setPosition(...p); if (collider) entity.addComponent(new BoxCollider(entity, new THREE.Vector3(...size))); const mesh = new THREE.Mesh(new THREE.BoxGeometry(...size), Material.basic(color)); mesh.castShadow = mesh.receiveShadow = true; entity.sceneObject.add(mesh); return entity; }
box('Range floor',[0,-.5,0],[70,1,70],0x172b37); for(const [x,z,sx,sz] of [[0,-35,70,1],[0,35,70,1],[-35,0,1,70],[35,0,1,70]])box('Range wall',[x,3,z],[sx,7,sz],0x112b39); for(let x=-24;x<=24;x+=12)box('Cover',[x,1.2,-8],[4,2.4,2],0x29485a);
for(const [x,z,c] of [[-18,-18,0x12e0c0],[18,-18,0xffb84e],[-18,18,0xff5883],[18,18,0x8d6dff]]){const light=new THREE.PointLight(c,16,16);light.position.set(x,5,z);world.add(light)}

const player=engine.createEntity('Player');player.setPosition(0,1.8,22);player.addComponent(new BoxCollider(player,new THREE.Vector3(.8,1.8,.8)));const controller=player.addComponent(new CharacterController(player,engine.input,engine.camera,engine.physics));controller.speed=6;controller.sprintSpeed=11;controller.jumpForce=8.4;engine.camera.follow(player);

// Procedural first-person blaster asset: body, barrel, sight, energy core and muzzle flash.
const gun=new THREE.Group();gun.position.set(.42,-.38,-.72);gun.rotation.set(-.08,-.08,0);const gunMat=Material.metal(0x263847), trim=Material.emissive(0x00e8bd,.7), dark=Material.basic(0x0b1118);const part=(geometry,material,p,r=[0,0,0])=>{const m=new THREE.Mesh(geometry,material);m.position.set(...p);m.rotation.set(...r);m.castShadow=true;gun.add(m);return m};part(new THREE.BoxGeometry(.28,.2,.65),gunMat,[0,0,0]);part(new THREE.CylinderGeometry(.055,.07,.55,10),dark,[0,.02,-.55],[Math.PI/2,0,0]);part(new THREE.BoxGeometry(.16,.2,.22),dark,[0,-.16,.12],[0,0,-.2]);part(new THREE.BoxGeometry(.08,.09,.18),trim,[0,.14,-.1]);const core=part(new THREE.SphereGeometry(.075,12,8),trim,[0,.02,-.18]);const flash=new THREE.PointLight(0x8affde,0,5);flash.position.set(0,.02,-.88);gun.add(flash);engine.camera.camera.add(gun);

const targets=[];const raycaster=new THREE.Raycaster();const centre=new THREE.Vector2();let score=0,combo=0,ammo=12,reloading=0,lastShot=0,fireKick=0;
function spawnTarget(position, moving=false){const root=new THREE.Group();root.position.set(...position);root.userData={health:1,moving,phase:Math.random()*6.2,baseX:position[0]};const ring=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.05,.13,32),Material.emissive(0x00cfa7,.25));ring.rotation.x=Math.PI/2;ring.castShadow=true;const face=new THREE.Mesh(new THREE.CylinderGeometry(.76,.76,.145,32),Material.basic(0xe9eef2));face.rotation.x=Math.PI/2;const bull=new THREE.Mesh(new THREE.CylinderGeometry(.25,.25,.16,24),Material.emissive(0xff3f6d,.55));bull.rotation.x=Math.PI/2;root.add(ring,face,bull);root.userData.target=root;world.add(root);targets.push(root)}
[[0,1.8,-20],[-8,2,-15],[8,2,-15],[-15,3,-24],[15,3,-24],[0,5,-29]].forEach((p,i)=>spawnTarget(p,i%2===1));
function fire(){if(reloading>0||ammo<=0){if(ammo<=0)reload();return}const now=performance.now()/1000;if(now-lastShot<.13)return;lastShot=now;ammo--;fireKick=.12;flash.intensity=10;raycaster.setFromCamera(centre,engine.camera.camera);const hit=raycaster.intersectObjects(targets,true)[0];if(hit){let target=hit.object;while(target&&!target.userData.target)target=target.parent;if(target){world.remove(target);targets.splice(targets.indexOf(target),1);score+=100+combo*25;combo++;spawnTarget([(Math.random()-.5)*26,1.5+Math.random()*4,-16-Math.random()*14],Math.random()>.45)}}else combo=0;updateHUD()}
function reload(){if(reloading>0||ammo===12)return;reloading=1.05;hint.textContent='Reloading…';updateHUD()}
function updateHUD(){scoreNode.textContent=String(score).padStart(6,'0');comboNode.textContent=combo>1?`COMBO ×${combo}`:'RANGE ONLINE';ammoNode.textContent=reloading>0?'RELOADING…':`${ammo} / 12`}
function reset(){score=combo=0;ammo=12;player.setPosition(0,1.8,22);controller.velocity.set(0,0,0);updateHUD();hint.textContent='Range reset'}
engine.onUpdate(delta=>{for(const target of targets){target.rotation.y+=delta*.75;const d=target.userData;if(d.moving)target.position.x=d.baseX+Math.sin(performance.now()/1000+d.phase)*3}if(engine.input.isMouseDown(0)&&document.pointerLockElement)fire();if(engine.input.isKeyPressed('KeyR'))reload();if(engine.input.isKeyPressed('KeyR')&&engine.input.keyboard.isDown('ShiftLeft'))reset();if(reloading>0&&(reloading-=delta)<=0){ammo=12;hint.textContent='';updateHUD()}fireKick=Math.max(0,fireKick-delta);gun.position.y=-.38-fireKick*.5;gun.rotation.x=-.08+fireKick*.35;core.scale.setScalar(1+fireKick*3);flash.intensity=Math.max(0,flash.intensity-delta*65);cross.classList.toggle('fire',fireKick>0);});
window.addEventListener('click',()=>{if(!engine.paused){engine.input.lockMouse();hint.textContent=''}});window.addEventListener('keydown',event=>{if(event.code==='Escape'){event.preventDefault();if(engine.paused){engine.resume();pauseScreen.classList.remove('show');engine.input.lockMouse()}else{engine.pause();document.exitPointerLock();pauseScreen.classList.add('show')}}if(event.code==='KeyR'&&event.shiftKey)reset()});
updateHUD();setTimeout(()=>document.querySelector('#loading').classList.add('done'),550);engine.start();
